language: node_js
node_js: 12

install:
  - npm i
  - npm i --prefix examples/react-webpack
  - npm i --prefix examples/vue-webpack

script:
  - npm run build
  - npm run build:examples

before_deploy:
  - sed -i '/dist/d' .gitignore
  - sed -i '/\/build/d' examples/react-webpack/.gitignore
  - sed -i '/\/dist/d' examples/vue-webpack/.gitignore
  - rm examples/superhero-utils
  - cp -r dist examples/superhero-utils

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: examples
    on:
      branch: master
