language: node_js
node_js: 12

install:
  - npm i
  - npm i --prefix examples/react-webpack
  - npm i --prefix examples/vue-webpack

script:
  - npm run build
  - npm run build:examples

deploy:
  - provider: script
    skip_cleanup: true
    script: sed -i '/dist/d' .gitignore
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: .
    on:
      branch: master
